spring.application.name=money-flow

money-flow.statements-api.base-url=http://localhost:8081
money-flow.statements-api.timeout=5s
money-flow.summary-api.base-url=http://localhost:8081
money-flow.summary-api.timeout=5s
